dk_log.pdf:Head.tex Bib.bib dk_log.tex chapters/To-Readers.tex chapters/Operating_system.tex chapters/Software.tex chapters/Server.tex
	latexmk -xelatex dk_log.tex
distclean:
	rm dk_log.pdf
.PHONY:clean
clean:
	rm *.*[!ei]?
	rm chapters/*.*[!e]?

