tuzhi.pdf:kaoshi.tex structure.tex 202307.tex 202311.tex 202312.tex 202402.tex 202403.tex 202404.tex 202407.tex 202409.tex
	latexmk -xelatex kaoshi.tex
distclean:
	rm kaoshi.pdf
.PHONY:clean
clean:
	rm *.*[!e]?
