tuzhi.pdf:tuzhi.tex structure.tex feedervalue.tex feeder.tex sootblower.tex sootblowerTON.tex packer.tex huan.tex
	latexmk -xelatex tuzhi.tex
distclean:
	rm tuzhi.pdf
.PHONY:clean
clean:
	rm *.*[!e]?
